---Sales Data Analysis 

--PROFIT ANALYSIS
	-- Total Profit
select sum(profit)
as total_profit 
from brew_data;

	-- Which brand sold the highest quantity in each country, and what was its total profit?

select brands, countries, total_quantities_sold, total_profit 
from (
select countries, brands, sum(quantity) as total_quantities_sold, sum(profit) as total_profit,
row_number() over (partition by countries order by sum(quantity) desc) as number
from brew_data
group by countries, brands)
as top_ranked_brands
where number = 1;


	---What is the most popular brand (by quantity sold) in the South-South region of Nigeria?"
WITH BrandTotals AS (
    SELECT
        brands,
        SUM(quantity) AS favourite_brands_southsouth_nigeria
    FROM brew_data
    WHERE region = 'southsouth'
      AND countries = 'nigeria'
    GROUP BY brands
)
SELECT TOP 1
    brands,
    favourite_brands_southsouth_nigeria
FROM BrandTotals
ORDER BY favourite_brands_southsouth_nigeria DESC;


	-- What is the total profit generated by Anglophone territories (Nigeria, Ghana) compared to Francophone territories (Senegal, Togo, Benin)?
select 
    sum(case 
            when countries in ('nigeria', 'ghana') then profit 
            else 0 
        end) as anglophone_territories,
    sum(case 
            when countries in ('senegal', 'togo', 'benin') then profit 
            else 0 
        end) as francophone_territories
from brew_data;

	--- Which year generated the highest total profit?
select years, 
sum(profit) as total_profit
from brew_data
group by years
order by total_profit desc;

	---Which months generate the highest total profit, and what is the average profit per month?
select months, sum(profit) as total_profit_by_months, 
avg(profit) as avg_profit_by_months
from brew_data
group by months
order by total_profit_by_months desc;

	-- Which countries generate the highest total profit?
select countries, sum(profit)as total_profit_by_countries
from brew_data
group by countries
order by total_profit_by_countries desc;

	-- Which country generated the highest total profit in 2019?
select top 1
        countries,
        sum(profit) as total_profit_2019
    from brew_data
    where years = 2019
	group by countries
    order by total_profit_2019 desc;

	-- Which year had the highest total profit?
select top 1
        years,
        sum(profit) as year_with_highest_total_profit
    from brew_data
	group by years
order by year_with_highest_total_profit desc;

	--- Which month had the lowest total profit?
select top 1
	months,
	sum(profit) as month_with_least_profit
	from brew_data
	group by months
	order by month_with_least_profit asc;

	--- What was the lowest profit recorded in December 2018?
select	min(profit) as min_profit_dec_2018
	from brew_data
	where months = 'december'
	and years = 2018
	group by months, years;

	--- What is the monthly profit percentage for 2019, and how do months compare in profitability?
select months,
 sum(profit) * 100.0 / sum(sales) as '2019_monthly_profit_percentage'
from brew_data
where years = 2019
group by months
order by '2019_monthly_profit_percentage';

	---Which brand generated the highest total profit in Senegal?
select top 1
	brands,
	sum(profit) as brand_with_highest_profit_senegal
	from brew_data
	where countries ='senegal'
	group by brands
	order by brand_with_highest_profit_senegal desc;

---SALES TEAM ANALYSIS

	---Which sales representative achieved the highest total sales, and how do they compare in terms of quantity sold?
select sales_rep,
sum(quantity) as total_quantity,
sum(sales) as total_sales 
from brew_data
group by sales_rep
order by total_sales desc;

select sales_rep,
sum(sales) as total_sales,
count(sales_id) as total_deals,
avg(sales) as avg_sales
from brew_data
group by sales_rep
order by total_sales desc;

select sales_rep, brands, 
sum(sales) as total_sales,
count(sales_id) as total_deals
from brew_data
group by sales_rep, brands
order by total_sales desc;

select sales_rep, countries, 
count(sales_id) as total_deals,
sum(sales) as country_sales
from brew_data
group by sales_rep, countries
order by country_sales desc;

select sales_rep, countries, 
count(sales_id) as total_deals,
sum(sales) as total_sales
from brew_data
group by sales_rep, countries
order by total_sales desc;

select sales_rep, countries, count(sales_id) as total_deals,
sum(sales) as country_sales from brew_data
group by sales_rep, countries
order by country_sales desc;

---BRAND AND TERRITORY ANALYSIS

alter table brew_data
add territories varchar (50) default null;

update brew_data
set territories = case 
    when countries = 'nigeria' then 'anglophone_territories'
    when countries = 'ghana' then 'anglophone_territories'
    else 'francophone_territories'
end; 
 
 select top 3
    brands,
    sum(quantity) as total_quantity
from brew_data
where territories = 'francophone_territories' 
    and years in ('2018', '2019') 
group by brands 
order by total_quantity desc; 

select brands, sum(profit) as total_profit_brands
from brew_data
group by brands
order by total_profit_brands desc; 

select brands, countries, sum(quantity) as total_quantities_sold
from brew_data
group by brands, countries
order by total_quantities_sold desc;



select top 2
brands,
sum(quantity) as total_quantity
from brew_data
where countries = 'ghana'
group by brands
order by total_quantity desc;
 
select brands, 
  sum(quantity) as total_units_purchased
  from brew_data
  where countries = 'nigeria'
  group by brands
  order by total_units_purchased desc;
  

select top 1 brands,
	sum(quantity) as top_malt_anglophone
	from brew_data
	where brands in ('beta malt', 'grand malt')
	and years in ('2018', '2019')
	and territories = 'anglophone_territories'
	group by brands
	order by top_malt_anglophone desc;

select top 1
brands,
sum(quantity) as '2019_top_brand'
from brew_data
where countries = 'nigeria'
and years= 2019
group by brands
order by '2019_top_brand' desc;

select top 1
brands,
sum(quantity) as favourite_brands_southsouth_nigeria
from brew_data
where region = 'southsouth'
and countries = 'nigeria'
group by brands
order by favourite_brands_southsouth_nigeria desc;

select sum(quantity) as beer_consumption_nigeria
from
    brew_data
where
    brands not like '%malt'
    and countries = 'nigeria';

select brands,
sum(quantity) as budweiser_consumption_nigeria
from brew_data
where brands = 'budweiser'
and countries = 'nigeria'
group by brands;

select region,
sum(quantity) as '2019_budweiser_consumption_nigeria'
from brew_data
where brands = 'budweiser'
and years = '2019'
and countries = 'nigeria'
group by region
order by '2019_budweiser_consumption_nigeria' desc;

---COUNTRY ANALYSIS

select countries, COUNT(SALES_ID) as Order_by_Countries
from BREW_DATA
group by COUNTRIES
order by Order_by_Countries desc;

select countries, sum(quantity) as total_quantities_by_countries
from brew_data
group by countries
order by total_quantities_by_countries desc;

select countries, brands, count(sales_id) as total_orders, 
sum(quantity) as total_quantity, avg(quantity) as avg_quantity_per_order
from brew_data
group by countries, brands
order by total_quantity desc;

select
top 1 countries,
sum(quantity) as country_with_beer_highest_consumption
from brew_data
where brands not like '%malt'
group by countries
order by country_with_beer_highest_consumption desc;

select top 1 sales_rep,
sum(quantity) as sales_rep_with_highest_sales
from brew_data
where countries = 'senegal'
and brands = 'budweiser'
group by sales_rep
order by sales_rep_with_highest_sales desc;

select top 1 countries,
sum(profit) as country_with_highest_profit_4th_quarter_2019
from brew_data
where months in('october', 'november', 'december')
and years = '2019'
group by countries
order by country_with_highest_profit_4th_quarter_2019 desc;

